FROM openjdk:18-jdk-alpine

RUN apk add --no-cache bash dumb-init

RUN mkdir -p /app
COPY java-run.sh /app
RUN chmod +x /app/java-run.sh

# Add our service
COPY target/*.jar /app/application.jar

# Add a NON-root user to run the app
RUN addgroup -S nonroot && adduser --disabled-password --system --uid 1000 --home /app --gecos "" -S nonroot -G nonroot && chown -R nonroot:nonroot /app

USER nonroot
WORKDIR /app

# run application with this command line
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
#CMD ["bash", "-c", "do-some-pre-start-thing && exec my-server"]
# The 'exec' portion of the bash command is important because it replaces the bash process with your server, so that the shell only exists momentarily at start!
#CMD ["bash", "-c", "echo 'Using dumb-init as entrypoint then starting spring-boot...' && exec $JAVA_HOME/bin/java $JAVA_OPTIONS -jar /app/application.jar $@"]
CMD ["bash", "-c", "echo 'Using dumb-init as entrypoint and a shell script as a pre-start hook and then starting spring-boot...' && /app/java-run.sh"]