FROM amazoncorretto:21-alpine-jdk

RUN apk add --no-cache bash

RUN mkdir -p /app
COPY java-run-non-graceful.sh /app
RUN chmod +x /app/java-run-non-graceful.sh

# Add our service
COPY target/*.jar /app/application.jar

# Add a NON-root system user to run the app
ARG USERNAME=nonroot
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN addgroup --gid $USER_GID $USERNAME \
    && adduser --system --no-create-home --gecos "" --uid $USER_UID -S $USERNAME -G $USERNAME \
    && chown -R $USERNAME:$USERNAME /app

USER $USERNAME
WORKDIR /app

# run application with this command line
# CMD ["/opt/openjdk-18/bin/java", "-jar", "-Dspring.profiles.active=default", "/app/application.jar"]
ENTRYPOINT ["/app/java-run-non-graceful.sh"]
