apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: k8s-spring-boot-graceful-shutdown
  description: A simple Microservice API
  tags:
    - spring-boot
    - rest
  links:
    - url: https://github.com/silverdonkey/k8s-spring-boot-graceful-shutdown
      title: GitHub Repo
      icon: github
    - url: https://github.com/silverdonkey/k8s-spring-boot-graceful-shutdown/blob/master/service-api.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: silverdonkey
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Swagger Spring Boot Demo
      license:
        name: MIT
    paths:
      /entity/all:
        get:
          summary: List all entities
          operationId: listAllEntities
          tags:
            - entities
          responses:
            '200':
              description: A list of entities
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/GenericEntities"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
      /entity:              
        post:
          summary: Create an entity
          operationId: createEntity
          tags:
            - entities
          responses:
            '201':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
      /entity/findby/{id}:
        get:
          summary: Info for a specific entity
          operationId: showEntityById
          tags:
            - entities
          parameters:
            - name: id
              in: path
              required: true
              description: The id of the entity to retrieve
              schema:
                type: string
          responses:
            '200':
              description: Expected response to a valid request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/GenericEntity"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    components:
      schemas:
        GenericEntity:
          type: object
          required:
            - id
            - value
          properties:
            id:
              type: integer
              format: int64
            value:
              type: string
            tag:
              type: string
        GenericEntities:
          type: array
          items:
            $ref: "#/components/schemas/GenericEntity"
        Error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
