name: Build and Deploy

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }}/.m2 # location for the settings.xml file

      - name: Deploy release with Maven Release Plugin
        run: |
          git config user.email "silverdonkey@users.noreply.github.com"
          git config user.name "SilverDonkey"
          mvn --batch-mode release:prepare release:perform -s $GITHUB_WORKSPACE/.m2/settings.xml
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn --batch-mode deploy -s $GITHUB_WORKSPACE/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
